version: '3'

services:
  postgres:
    image: postgres:14.4-alpine
    ports:
      - '0.0.0.0:${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - base_project
    healthcheck:
      test: ['CMD', 'postgresql', 'ping']
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - ./.data/redis:/data
    networks:
      - base_project
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
networks:
  base_project:
    driver: bridge